### ISSUE TITLE
Hilfe installation 

### ISSUE THREAD

**Issue by Laro5444** [Neocraftr/griefergames-afk-bot#1]
Hi Neocraftr
Ich hätte mal 2 kurze Fragen. 
Und zwar ist es möglich dieses Programm auf labbymod zu benutzen da mein Verkaufsbot über labbymod läuft. 
Und wen  ja könntest du mir kurz helfen es zu Installieren? 
Wäre wirklich nett wenn du mir dies beantworten kannst :).

**Comment by Neocraftr** [comment]
Der Bot ist komplett unabhängig vom offiziellen Spiel und kann somit leider nicht zusammen mit dem normalen Minecraft, Forge oder LabyMod verwendet werden
